# Generated by Django 3.2 on 2022-11-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.BigIntegerField(blank=True, null=True, verbose_name='镜像id')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='镜像名称')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='标签')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('mem', models.IntegerField(blank=True, null=True, verbose_name='大小')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='课程名称')),
                ('env', models.CharField(blank=True, max_length=500, null=True, verbose_name='实验环境')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='选课人数')),
                ('create_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.image')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Containerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.IntegerField(blank=True, null=True, verbose_name='容器id')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='容器名')),
                ('run_time', models.DateTimeField(blank=True, null=True, verbose_name='开始运行时间')),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP地址')),
                ('port', models.BigIntegerField(blank=True, null=True, verbose_name='端口号')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.image')),
            ],
            options={
                'db_table': 'ContainerList',
            },
        ),
    ]
